
name: Atualizar clientes

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  atualizar:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Verificar banco JSON
      run: |
        echo "Banco preparado"
        cat clientes.json
