
name: Salvar clientes

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  salvar:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Preparar ambiente
      run: |
        echo "Sistema conectado ao GitHub Actions"

    - name: Banco JSON
      run: |
        cat clientes.json
